-- hash bcrypt
-- toanqc / toanqc
-- admin / admin
-- user / user

INSERT INTO User (USERNAME, `PASSWORD`, ENABLED) values ('admin', '$2a$08$EWvyxB5sKHyPTMmDZFU3buZ30OIUlvTr/jpniiOgiBQ270T/Lgpo.', TRUE);
INSERT INTO User (USERNAME, `PASSWORD`, ENABLED) values ('user', '$2a$08$15l95Q4n/NpESig4HuEOzeieIpb0d.I0F5EH3w0nX8lMoI4NXOd16', TRUE);

INSERT INTO Authority (USERNAME, AUTHORITY) values ('admin', 'ROLE_ADMIN');
INSERT INTO Authority (USERNAME, AUTHORITY) values ('user', 'ROLE_USER');

INSERT INTO EntryDetail (CONTENT) values ('<p><img style="display: block; margin-left: auto; margin-right: auto;" src="https://infosys.cs.mum.edu/infosys/images/mum-logo.jpg" alt="Logo" width="128" height="146" /></p><p>I&rsquo;m very excited to let you know that I&rsquo;m joining <a href="http://www.mum.edu">M.U.M</a>.</p><p>After ten years experience worked in my country&nbsp;I couldn&rsquo;t be more proud. Proud to have been part of something as important and proud of the work I&rsquo;ve done with shaping the future of mobile communication. It&rsquo;s truly been a fantastic time of my life &mdash; an experience rich of great people, mind-boggling challenges and once-in-a-lifetime experiences.</p><blockquote><p>Look at the past for inspiration, but focus on the future, because tomorrow is shaped by the choices we make today.</p></blockquote><p>At M.U.M I&rsquo;m going to study / work hard to make all our lives better. Remove friction from technical details in our modern daily lives, and relieve us from worrying about our &ldquo;stuff&rdquo; &mdash; from quick snapshots and hasty notes to precious memories.</p><p>This is going to be such a fun adventure.</p>');
INSERT INTO EntryDetail (CONTENT) values ('<p class="p1">I am going to take EA (Enterprise Architecture this block. I am very interested in this course since I think there will be a lot of valuable knowledge during the course.</p><h1 class="p1">Spring / Hibernate</h1><p class="p1">I know a lot about Spring <span class="s1">and</span> Hibernate but I think they are huge framework <span class="s1">and</span> so much more information to discover.</p><h2>Course Structure:</h2><ol><li>Week 1:<ol><li class="p1">Intro &amp; Entity Mapping</li><li class="p1">Associations &amp; Collections</li><li class="p1">Inheritance &amp; Complex</li><li class="p1">HQL &amp; Concurency</li><li class="p1">Optimization</li></ol></li><li class="p1">Week 2:<ol><li class="p1">Java Web &amp; Hibernate Apps</li><li class="p1">Containers &amp; DI</li><li class="p1">Services &amp; AOP</li><li class="p1">Spring &amp; Hibernate</li><li class="p1">Transactions &amp; Scheduling</li></ol></li><li class="p1">Week 3:<ol><li class="p1">Spring MVC</li><li class="p1">Security &amp; Validation</li><li class="p1">RMI &amp; JMS</li><li class="p1">Spring Web Services</li></ol></li><li class="p1">Week 4:<ol><li class="p1">Project</li></ol></li></ol><p>&nbsp;</p>');
INSERT INTO EntryDetail (CONTENT) values ('<p class="p1">I am sadly to say that I am going to leave AdNovum Company within this month, since that I decided to pursue my MSCS degree in the United States</p><h2 class="p1">Opportunity Ahead</h2><p class="p1">This is very hard decision but I think it will be the best choice for me to improve my professional skill by having a chance to work in the United States after 8 months study in the campus.</p>');
INSERT INTO EntryDetail (CONTENT) values ('<h1><img style="float: right;" title="TinyMCE Logo" src="http://www.tinymce.com/tryit/img/tlogo.png" alt="TinyMCE Logo" width="92" height="80" />Welcome to the TinyMCE editor demo!</h1><p>Feel free to try out the different features that are provided, please note that the <strong>MoxieManager</strong> specific functionality is part of our commercial offering. The demo is to show the integration.</p><h2>Got questions or need help?</h2><p>If you have questions or need help, feel free to visit our <a href="../forum/index.php">community forum</a>! We also offer Enterprise <a href="../enterprise/support.php">support</a> solutions. Also do not miss out on the <a href="../wiki.php">documentation</a>, its a great resource wiki for understanding how TinyMCE works and integrates.</p><h2>Found a bug?</h2><p>If you think you have found a bug, you can use the <a href="../develop/bugtracker.php">Bug Tracker</a> to report bugs to the developers.</p><p>And here is a simple table for you to play with.</p><table border="0"><tbody><tr><td><strong>Product</strong></td><td><strong>Cost</strong></td><td><strong>Really?</strong></td></tr><tr><td>TinyMCE</td><td>Free</td><td>YES!</td></tr><tr><td>Plupload</td><td>Free</td><td>YES!</td></tr></tbody></table><p>Enjoy our software and create great content!</p><p>Oh, and by the way, do not forget to check out our other product called <a href="http://www.plupload.com" target="_blank">Plupload</a>, your ultimate upload solution with HTML5 upload support!</p>');
INSERT INTO EntryDetail (CONTENT) values ('<p>There was a lot of new knowledges in EA course that I have never know before. Basically I listed some of them below</p><h2>New Annotation Knowledge:</h2><ol><li>@Inheritance(stragety=SINGLE_TABLE | TABLE_PER_CONCRETE_CLASS, JOINED): use for Inheritance Mapping</li><li>@Embeddable, @Embededed: Complex Mapping</li><li>@Version: use for Optimistic Concurrency</li></ol><h2>New Knowledage About ISOLATION:</h2><ol><li>Read Uncommited</li><li>Read Commited</li><li>Repeatable Read</li><li>Serializable</li></ol>');

INSERT INTO Entry (TITLE, SHORT_DESCRIPTION, CREATED_DATE, USER_ID, ENTRY_DETAIL_ID) values ('Joined M.U.M', 'I’m very excited to let you know that I’m joining M.U.M. After ten years experience worked in my country I couldn’t be more proud. Proud to have been part of something as important and proud of the work I’ve done with shaping the future of mobile communication', '2015-05-30', 1, 1);
INSERT INTO Entry (TITLE, SHORT_DESCRIPTION, CREATED_DATE, USER_ID, ENTRY_DETAIL_ID) values ('Take EA course', 'I am going to take EA (Enterprise Architecture this block. I am very interested in this course since I think there will be a lot of valuable knowledge during the course', '2015-10-05', 1, 2);
INSERT INTO Entry (TITLE, SHORT_DESCRIPTION, CREATED_DATE, USER_ID, ENTRY_DETAIL_ID) values ('Leaving AdNovum', 'I am sadly to say that I am going to leave AdNovum Company within this month, since that I decided to pursue my MSCS degree in the United States', '2015-04-25', 1, 3);
INSERT INTO Entry (TITLE, SHORT_DESCRIPTION, CREATED_DATE, USER_ID, ENTRY_DETAIL_ID) values ('Using TinyMCE in blog website', 'TinyMCE is a platform independent web-based JavaScript WYSIWYG HTML editor control released as open source under LGPL', '2015-11-16', 1, 4);
INSERT INTO Entry (TITLE, SHORT_DESCRIPTION, CREATED_DATE, USER_ID, ENTRY_DETAIL_ID) values ('New Knowledges', 'There was a lot of new knowledge in EA course that I have never know before. Basically I listed some of them below', '2015-11-01', 1, 5);